expedienteclinico/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from paciente import views
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('',views.inicio),
    path('admin/', admin.site.urls),
    path('busca-general/<int:dato>/<int:propietario>',views.consultaDatoGeneral,name='bucatageneral'),
    path('paciente/',include('paciente.urls')),
]
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$',serve, {
        'document_root':settings.MEDIA_ROOT
    }),
]

paciente/urls.py
from django.urls import path
from paciente import views
urlpatterns = [
    path('',views.inicio,name='paciente'),
    path('registro-general/',views.formGeneral,name='verpaciente'),
    path('consulta/',views.consultaPacientes,name='consultapaciente'),
    path('consulta-ajax/',views.consultaPacientesajax ,name='consultapacienteajax'),
    path('nuevo/', views.nuevoPaciente,name='nuevopaciente'),
    path('editar/<int:dato>', views.editarPaciente,name='editarpaciente'),
    path('editar/paciente/<int:dato>', views.editarPacienteAjax,name='editarpacienteajax'),
    path('editar-preferencia/<int:prefe>', views.editarPreferencia,name='editarprefe'),
    path('editar-datos-generales/<int:datogeneral>', views.editarDatoGeneral,name='editardatogeneral'),
    path('editar-heredo-familiar/<int:heredofamiliar>', views.editarHeredoFamiliar,name='editarheredofamiliar'),
    path('editar-patologias/<int:patologico>', views.editarPatologicos,name='editarpatologicos'),
    path('editar-no-patologias/<int:patologico>', views.editarNoPatologicos,name='editarnopatologicos'),
    path('editar-habitos-alimenticios/<int:habito>', views.editaHalimenticio,name='editaralimenticio'),
    path('editar-exploracion/<int:exploracion>', views.editaExploracion,name='editarexploracion'),
    path('editar-sangre/<int:sangre>', views.edtirarSangre,name='editarsangre'),
    path('editar-sexo/<int:sexo>', views.edtirarSexo,name='editarsexo'),
    path('editar-notas/<int:notas>', views.edtirarNotas,name='editarnotas'),
]

paciente/models.py
from django.db import models
from django.db.models.signals import post_save
from multiselectfield import MultiSelectField
MY_CHOICES2 = ((1, 'Desayuno'),
               (2, 'Desayuno'),
               (3, 'Almuerzo'),
               (4, 'Comida'),
               (5, 'Colaciones'))

# Create your models here.


class TipoUsuario(models.Model):
    nombre = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return f'Tipo usuario: {self.nombre} id: {self.id}'


class TipoSangre(models.Model):
    nombre = models.CharField(max_length=8, blank=True, null=True)

    def __str__(self):
        return f'{self.nombre}'


class TipoSexo(models.Model):
    nombre = models.CharField(max_length=8, blank=True, null=True)

    def __str__(self):
        return f'{self.nombre}'


class Paciente(models.Model):
    tipo_usuario = models.ForeignKey(
        TipoUsuario, verbose_name='Tipo de usuario', on_delete=models.PROTECT)
    tipo_sangre = models.ForeignKey(
        TipoSangre, verbose_name='Tipo de sangre', on_delete=models.PROTECT)
    tipo_sexo = models.ForeignKey(
        TipoSexo, verbose_name='Tipo de sexo', on_delete=models.PROTECT)
    nombre = models.CharField(max_length=25)
    apellido = models.CharField(max_length=100)
    telefono = models.CharField(max_length=10, blank=True, null=True)
    foto = models.ImageField(
        upload_to='fotopaciente/%Y/%m/%d', null=True, blank=True)
    email = models.EmailField(
        verbose_name='correo electronico', blank=True, null=True)
    empresa = models.CharField(max_length=150, blank=True, null=True)

    def __str__(self):
        return f'id: {self.id} Usuario: {self.nombre} tipo usuario: {self.tipo_usuario}'


class DatosGeneral(models.Model):
    propietario = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    celular = models.CharField(max_length=10, blank=True, null=True)
    telefono = models.CharField(max_length=10, blank=True, null=True)
    domicilio = models.CharField(max_length=150, blank=True, null=True)
    ciudad = models.CharField(max_length=150, blank=True, null=True)
    estado = models.CharField(max_length=150, blank=True, null=True)
    cp = models.PositiveIntegerField(blank=True, null=True)
    lugar_nacimiento = models.CharField(max_length=150, blank=True, null=True)
    ocupacion = models.CharField(max_length=50, blank=True, null=True)
    region = models.CharField(max_length=50, blank=True, null=True)
    clave_app = models.CharField(max_length=10, blank=True, null=True)
    datofiscal = models.FileField(
        upload_to='datofiscal/%Y/%m/%d', null=True, blank=True, verbose_name='Curriculum vitae')

    def __str__(self):
        return f'Id: {self.id} {self.propietario}'


class Preferencia(models.Model):
    propietario = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    experiencia = models.TextField(
        max_length=200, null=True, blank=True, verbose_name='')
    nombre_pareja = models.CharField(
        max_length=25, blank=True, null=True, verbose_name="")
    fecha_aniversario = models.DateField(
        blank=True, null=True, verbose_name='')
    nombre_hijos = models.CharField(
        max_length=25, blank=True, null=True, verbose_name="")
    fecha_hijo = models.DateField(blank=True, null=True, verbose_name="")
    nombre_empresa = models.CharField(
        max_length=50, blank=True, null=True, verbose_name="")
    gustos = models.CharField(
        max_length=50, blank=True, null=True, verbose_name="")
    fecha_empresa = models.DateField(blank=True, null=True, verbose_name="")
    deportes = models.CharField(
        max_length=150, blank=True, null=True, verbose_name="")
    pelicula_serie = models.CharField(
        max_length=150, blank=True, null=True, verbose_name="")
    musica = models.CharField(
        max_length=150, blank=True, null=True, verbose_name="")
    vehiculo = models.CharField(
        max_length=150, blank=True, null=True, verbose_name="")
    comida = models.CharField(
        max_length=150, blank=True, null=True, verbose_name="")


class NotaPaciente(models.Model):
    propietario = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    alergias = models.CharField(max_length=250, blank=True, null=True)
    expectativas = models.CharField(max_length=250, blank=True, null=True)
    pade_actual = models.CharField(max_length=250, blank=True, null=True)
    observaciones = models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        return f'{self.propietario}'


class AntecedentePersonal(models.Model):
    propietario = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    casa = models.CharField(max_length=25, blank=True, null=True)
    lav_dientes = models.CharField(max_length=25, blank=True, null=True)
    tipo_pasta = models.CharField(max_length=25, blank=True, null=True)
    amalgama_puente = models.CharField(max_length=25, blank=True, null=True)
    brakets = models.CharField(max_length=25, blank=True, null=True)
    actividad_fisica = models.CharField(max_length=25, blank=True, null=True)
    ultima_desparacita = models.CharField(max_length=25, blank=True, null=True)
    inmunizaciones = models.CharField(max_length=25, blank=True, null=True)
    check_up = models.CharField(max_length=25, blank=True, null=True)

    def __str__(self):
        return f'{self.propietario}'


class AntecedenteFamiliar(models.Model):
    propietario = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    hermanos = models.PositiveIntegerField(default=0)
    diabetes = models.CharField(max_length=25, blank=True, null=True)
    hip_arterial = models.CharField(max_length=25, blank=True, null=True)
    cardiopatias = models.CharField(max_length=25, blank=True, null=True)
    hepatopatias = models.CharField(max_length=25, blank=True, null=True)
    urologicos = models.CharField(max_length=25, blank=True, null=True)
    neurologicos = models.CharField(max_length=25, blank=True, null=True)
    respiratorios = models.CharField(max_length=25, blank=True, null=True)
    cancer = models.CharField(max_length=25, blank=True, null=True)
    alergias = models.CharField(max_length=25, blank=True, null=True)
    metabolicas = models.CharField(max_length=25, blank=True, null=True)
    sanguineas = models.CharField(max_length=25, blank=True, null=True)
    articulares = models.CharField(max_length=25, blank=True, null=True)
    inmunologicas = models.CharField(max_length=25, blank=True, null=True)
    malformaciones = models.CharField(max_length=25, blank=True, null=True)
    dermatologicas = models.CharField(max_length=25, blank=True, null=True)
    otros = models.CharField(max_length=25, blank=True, null=True)

    def __str__(self):
        return f'{self.propietario}'


class AntecedentePatologico(models.Model):
    propietario = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    enf_infancia = models.CharField(max_length=25, blank=True, null=True)
    diabetes = models.CharField(max_length=25, blank=True, null=True)
    hip_arterial = models.CharField(max_length=25, blank=True, null=True)
    respiratorias = models.CharField(max_length=25, blank=True, null=True)
    oftalmico = models.CharField(max_length=25, blank=True, null=True)
    cardeovasculares = models.CharField(max_length=25, blank=True, null=True)
    neurologicos = models.CharField(max_length=25, blank=True, null=True)
    gastro_intestinal = models.CharField(max_length=25, blank=True, null=True)
    hepaticas = models.CharField(max_length=25, blank=True, null=True)
    metabolicas = models.CharField(max_length=25, blank=True, null=True)
    urologicos = models.CharField(max_length=25, blank=True, null=True)
    circulatorio = models.CharField(max_length=25, blank=True, null=True)
    traumaticas = models.CharField(max_length=25, blank=True, null=True)
    articulares = models.CharField(max_length=25, blank=True, null=True)
    dermatologicas = models.CharField(max_length=25, blank=True, null=True)
    quirurgicas = models.CharField(max_length=25, blank=True, null=True)
    transfusionales = models.CharField(max_length=25, blank=True, null=True)
    alergias = models.CharField(max_length=25, blank=True, null=True)
    vectores = models.CharField(max_length=25, blank=True, null=True)
    autoimunes = models.CharField(max_length=25, blank=True, null=True)
    emocionales = models.CharField(max_length=25, blank=True, null=True)
    adicciones = models.CharField(max_length=25, blank=True, null=True)
    hosp_previas = models.CharField(max_length=25, blank=True, null=True)
    pesticidas = models.CharField(max_length=25, blank=True, null=True)
    dx_ca = models.CharField(max_length=25, blank=True, null=True)
    otros = models.CharField(max_length=25, blank=True, null=True)

    def __str__(self):
        return f'{self.propietario}'


class AntecedenteAlimenticio(models.Model):
    propietario = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    #  = models.CharField(max_length=50, blank=True, null=True)
    # comidaa = MultiSelectField(choices=COMIDAS)
    # my_field = MultiSelectField(choices=MY_CHOICES)
    # comidas = MultiSelectField(
    #     choices=MY_CHOICES2, max_choices=6, max_length=6, blank=True, null=True)
    desayuno = models.BooleanField(default=False)
    almuerzo = models.BooleanField(default=False)
    comida = models.BooleanField(default=False)
    cena = models.BooleanField(default=False)
    colaciones = models.BooleanField(default=False)
    tortillas = models.CharField(max_length=25, blank=True, null=True)
    pan = models.CharField(max_length=25, blank=True, null=True)
    cereales = models.CharField(max_length=25, blank=True, null=True)
    refrescos = models.CharField(max_length=25, blank=True, null=True)
    jugos = models.CharField(max_length=25, blank=True, null=True)
    aguas_frescas = models.CharField(max_length=25, blank=True, null=True)

templates/paciente/consultapaciente.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %}
consulta pacientes
{% endblock titulo %}

{% block cabeza %}
{% include 'paciente/menu.html' %}
{% endblock cabeza %}
{% block cuerpo %}
{% load crispy_forms_tags %}
<div class="col-12 col-md-12 col-lg-8" id="divPacientes">
    {% include 'paciente/recursos/modalnuevapaciente.html' %}
    <div class="card">
        <div class="card-body">
            <div id="cargaPacientes">
                <!-- quitaar -->
                <!-- <form action="" id="form-container">
                    <button type="submit" class="btn btn-success">Enviar</button>
                </form> -->
                <!-- quitaar -->
            </div>
            <!-- menu nuevo dato de la card -->
            {% include 'paciente/recursos/menucard.html' %}
            <!-- menu nuevo dato de la card -->
            {% include 'paciente/recursos/cuerpotabla.html' %}
            <!-- div del paciente  -->
            <!-- div del paciente  -->
        </div>
    </div>
</div>
<!-- tarjeta paciente -->
<div class="col-12 col-md-12 col-lg-4" id="divTarjetasPacientes">
    <div class="accordion md-accordion" id="tablerosPacientes" role="tablist" aria-multiselectable="true">
        <!-- Ultimas consultas -->
        <div class="card">
            {% include 'paciente/recursos/cardultimasconsultas.html' %}
        </div>
        <!-- Ultimas consultas -->
        <!-- proximas consutlas -->
        <div class="card">
            {% include 'paciente/recursos/cardproximaconsulta.html' %}
        </div>
        <!-- proximas consutlas -->
        <!-- cumpleaños -->
        <div class="card">
            {% include 'paciente/recursos/cardcumple.html' %}
        </div>
        <!-- cumpleaños -->

    </div>

    <div id="divDetalleContacto"></div>


</div>
<!-- tarjeta paciente -->

{% endblock cuerpo %}

{% block scriptss %}
<script>
    function handleGetDatoResponse(data) {
        var formContainer = document.getElementById("form-container");
        formContainer.innerHTML = data.form_html;
    }

    function formpedir() {
        /*
        fetch('http://127.0.0.1:8000/paciente/editar/paciente/97')
        .then(response => response.json())
        .then(response=>{
            console.log(response)
            //handleGetDatoResponse(response)
        });
        
        */
    }

    function nuevoPaciente() {
        $('#id_nombre').focus();
        $('#modalNuevoPaciente').modal('toggle');
    }

    function solicitudPacientes() {
        fetch('http://127.0.0.1:8000/paciente/consulta-ajax/').then(response => response.json()).then(response => {
            //console.log(response.datos);
            cargaPacientes.innerHTML = `
            <table class="table table-hover table-responsive-sm table-fixed mt-2">
                <thead class="blue lighten-4 ">
                    <tr>
                        <th width="62px;"></th>
                        <th style="font-size: 13px;">Contactos</th>
                        <th style="font-size: 13px;" width="25%;">Cita</th>
                    </tr>
                </thead>
                <tbody>      
            `
            response.datos.forEach((paciente, index) => {
                console.log('Indice: ' + index + ' Valor: ' + paciente.nombre + paciente.apellido);
                cargaPacientes.innerHTML += `
                <tr>
                    <td style="padding-left: 0; padding-right: 0;padding-top: 4px; padding-bottom: 1px;">
                        <a href="" target="_self">
    
                            <i class="fas fa-image text-muted fa-4x"></i>
    
                        </a>
                    </td>
    
                    <td style="font-size: 13px;">
                        <div class="row">
                            <div class="col-12 col-md-4" style="cursor: pointer;">
    
                                ${paciente.nombre} ${paciente.apellido}
                                <!--</a>-->
                                <br>
                                <a href="https://api.whatsapp.com/send?phone=+52{{paciente.telefono}}&amp;text=Hola, Obed, te contactamos de Clínica Cambrón"
                                    target="_blank">
                                    <i class="fab fa-whatsapp"></i>&nbsp;
                                    ${paciente.telefono} </a>
                            </div>
                            <div class="col-12 col-md-8">
                                <!-- Acapulco Guerrero <br> -->
                                <a href="mailto:${paciente.email}">
                                    <i class="far fa-envelope"></i>
                                    ${paciente.email} </a>
                            </div>
                            <div class="col-12 col-md-4">
                                <a href="tel:+52${paciente.telefono}">
                                    <i class="fas fa-phone-volume"></i>&nbsp;
                                    {{paciente.telefono}} </a>
                            </div>
                        </div>
    
                    </td>
                    <!-- <td style="font-size: 13px;">
                        <div class="row">
                            <div class="col-12 col-md-6">
                                "citadia" </div>
                            <div class="col-12 col-md-6">
                                "citahota"</div>
                        </div>
                    </td> -->
    
                </tr>
            `

            });
        })
        cargaPacientes.innerHTML += `  </tbody>
    </table>
    `
    }

    function guardaNuevoPaciente() {
        //document.getElementById('miText').disabled = true;
        var action = document.getElementById('formhola').action;
        fetch(`${action}`, {
            method: 'POST',
            body: new FormData(formhola),
        }).then(response => response.json()).then(response => {
            if (response.tipo === "success") {
                document.getElementById('formhola').reset();
                $('#modalNuevoPaciente').modal('hide')
                Swal.fire({
                    icon: 'success',
                    title: 'Registrado correctamente',
                    showConfirmButton: false,
                    timer: 1500
                })
                location.reload()
                return false;
            }
            /*
             if (response.tipo === "success") {
                document.getElementById('formhola').reset();
                $('#modalNuevoPaciente').modal('hide')
                Swal.fire({
                    icon: 'success',
                    title: 'Registrado correctamente',
                    showConfirmButton: false,
                    timer: 1500
                })
                return false;
            }
              else if(response.success == false){
                  var example_form = document.getElementById('formhola');
                  $(example_form).find('.error-message').show()
              }
            */
        })

    }
</script>
{% endblock scriptss %}

templates/paciente/consutlaindividual.html
{% extends 'base.html' %}

{% block titulo %}
consulta
{% endblock titulo %}

{% block cuerpo %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="row mt-3">
    
        <div class="col-6">
            <form method="POST" action="" autocomplete="off">
                <h1 class="text-center">consulta</h1>
                <div class="card-body">
                    {{formpacientegeneral}}
                     <div class="form-group">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="gridCheck">
                            <label class="form-check-label" for="gridCheck">
                                Check me out
                            </label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Sign in</button>
                </div>
            </form>
        </div>
        <div class="col-6  text-center mt-2">
            <div class="form-check form-check-inline">
                <input class="form-check-input" onclick="consultapaciente();" type="radio" name="inlineRadioOptions"
                    id="inlineRadio1" value="option1">
                <label class="form-check-label" for="inlineRadio1">Paciente</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" onclick="consultapersonal();" name="inlineRadioOptions"
                    id="inlineRadio2" value="option2">

                <label class="form-check-label" for="inlineRadio2">Personal</label>
            </div>
            <div class="form-check form-check-inline">

                <input class="form-check-input" onclick="consultacontacto();" type="radio" name="inlineRadioOptions"
                    id="inlineRadio3" value="option2">
                <label class="form-check-label" for="inlineRadio3">Contacto</label>
            </div>
        </div>
        <div class="col-8  text-center mt-2">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Usuario</th>
                        <th scope="col">tipo</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
     
    </div>
</div>

<script>
    function solicitud() {

    }

    function consultapaciente() {
        alert('paciente');
    }

    function consultapersonal() {
        alert('personal');
    }

    function consultacontacto() {
        alert('contacto');
    }
</script>
{% endblock cuerpo %}
           

templates/paciente/formularios.html
<div class="col-12">
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-success">Insertar </button>
    </form>
</div>
<h1>formgeneral</h1>
<div class="col-12">

    {{formgeneral}}
</div>
<h1>formpref</h1>
<div class="col-12">

    {{formpref}}
</div>
<h1>formnota</h1>
<div class="col-12">
    {{formnota}}
</div>
<h1>formpersonal</h1>
<div class="col-12">
    {{formpersonal}}
</div>
<h1>formfamiliar</h1>
<div class="col-12">
    {{formfamiliar}}
</div>
<h1>formpatologico</h1>
<div class="col-12">
    {{formpatologico}}
</div>
<h1>formalimenticio</h1>
<div class="col-12">
    {{formalimenticio}}
</div>

templates/paciente/menu.html
{% load static %}

<header>
    <style type="text/css">
        .adqLicencia {
            background-color: red;
            color: #FFF;
            border-radius: 600px;
        }

        .adqLicencia:hover {
            background-color: red !important;
            color: yellow;
            border-radius: 600px;
        }
    </style>

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark special-color-dark scrolling-navbar">
        <div class="container-fluid">

            <a class="navbar-brand" href="#" style="margin-right:.1rem; margin-left: -1rem;">
                <div id="logoMenu">
                    <img src="{% static 'img/' %}maily.png" class="mx-auto" height="40px">

                </div>

            </a>

            <button class="navbar-toggler" type="button" style="padding: .25rem;" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav navbar-principal mr-auto">



                    <!-- MOVIMIENTOS -->
                    <li class="nav-item text-center  ">
                        <a class="nav-link waves-effect waves-light" href="../finanzas/" target="_self">
                            <img src="{% static 'img/' %}ico/indicadores.svg" width="30"> <br>
                            <span style="font-size: 12px;">Finanzas</span>
                        </a>
                    </li>
                    <!-- AGENDA -->
                    <li class="nav-item text-center">
                        <a class="nav-link waves-effect waves-light" href="../agenda/" target="_self">
                            <img src="{% static 'img/' %}ico/agenda.svg" width="30"> <br>
                            <span style="font-size: 12px;">Agenda   </span>
                        </a>
                    </li>
                    <!-- PACIENTES -->
                    <li class="nav-item text-center  {% if  request.resolver_match.url_name == 'consultapaciente' %} active {% endif %}">
                        
                        <a class="nav-link waves-effect waves-light  " href="{% url 'consultapaciente' %}" target="_self">
                            <img src="{% static 'img/' %}ico/pacientes.svg" width="30"> <br>
                            <span style="font-size: 12px;">
                                Contactos 
                            </span>
                        </a>
                    </li>
                </ul>


                <ul class="navbar-nav navbar-user">


                    <li class="nav-item dropdown">


                        <a class="nav-link dropdown-toggle waves-effect waves-light" href="#"
                            id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                            <i class="fas fa-id-card-alt text-white"></i> Prueba Programación 
                            
                                 </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">

                            <a class="dropdown-item waves-effect waves-light" href="#" target="_self">
                                Licencia: ESPECIALIZADO </a>

                            <a class="dropdown-item waves-effect waves-light">
                                Expira: 01/05/2023 </a>

                            <a class="dropdown-item waves-effect waves-light">
                                <small><i>Médico Titular</i></small> </a>


                            <a class="dropdown-item waves-effect waves-light"
                                href="https://api.whatsapp.com/send?phone=+527442298775&amp;text=Hola, necesito contactar un asesor de maily "
                                target="_blank"><i class="fas fa-hands-helping mr-2 text-success"></i>
                                Contacte un asesor
                            </a>
                            <a class="dropdown-item waves-effect waves-light" href="../estadoDeCuenta/"
                                target="_self"><i class="fas fa-cog mr-2 text-warning"></i>Estado de Cuenta</a>



                            <a class="dropdown-item waves-effect waves-light" href="../miConsultorio/"
                                target="_self"><i class="fas fa-clinic-medical mr-2 text-info"></i>
                                Mi Consultorio
                            </a>



                            <a class="dropdown-item waves-effect waves-light" href="../acceso/salir.php"
                                target="_self"><i class="fas fa-power-off mr-2 text-danger"></i>Salir</a>
                        </div>

                    </li>

                </ul>

            </div>

        </div>
    </nav>
</header>