expedienteclinico/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from paciente import views
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('',views.inicio),
    path('admin/', admin.site.urls),
    path('busca-general/<int:dato>/<int:propietario>',views.consultaDatoGeneral,name='bucatageneral'),
    path('paciente/',include('paciente.urls')),
]
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$',serve, {
        'document_root':settings.MEDIA_ROOT
    }),
]

paciente/urls.py
from django.urls import path
from paciente import views
urlpatterns = [
    path('',views.inicio,name='paciente'),
    path('registro-general/',views.formGeneral,name='verpaciente'),
    path('consulta/',views.consultaPacientes,name='consultapaciente'),
    path('consulta-ajax/',views.consultaPacientesajax ,name='consultapacienteajax'),
    path('nuevo/', views.nuevoPaciente,name='nuevopaciente'),
    path('editar/<int:dato>', views.editarPaciente,name='editarpaciente'),
    path('editar/paciente/<int:dato>', views.editarPacienteAjax,name='editarpacienteajax'),
    path('editar-preferencia/<int:prefe>', views.editarPreferencia,name='editarprefe'),
    path('editar-datos-generales/<int:datogeneral>', views.editarDatoGeneral,name='editardatogeneral'),
    path('editar-heredo-familiar/<int:heredofamiliar>', views.editarHeredoFamiliar,name='editarheredofamiliar'),
    path('editar-patologias/<int:patologico>', views.editarPatologicos,name='editarpatologicos'),
    path('editar-no-patologias/<int:patologico>', views.editarNoPatologicos,name='editarnopatologicos'),
    path('editar-habitos-alimenticios/<int:habito>', views.editaHalimenticio,name='editaralimenticio'),
    path('editar-exploracion/<int:exploracion>', views.editaExploracion,name='editarexploracion'),
    path('editar-sangre/<int:sangre>', views.edtirarSangre,name='editarsangre'),
    path('editar-sexo/<int:sexo>', views.edtirarSexo,name='editarsexo'),
    path('editar-notas/<int:notas>', views.edtirarNotas,name='editarnotas'),
]

paciente/models.py
from django.db import models
from django.db.models.signals import post_save
from multiselectfield import MultiSelectField
MY_CHOICES2 = ((1, 'Desayuno'),
               (2, 'Desayuno'),
               (3, 'Almuerzo'),
               (4, 'Comida'),
               (5, 'Colaciones'))

# Create your models here.


class TipoUsuario(models.Model):
    nombre = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return f'Tipo usuario: {self.nombre} id: {self.id}'


class TipoSangre(models.Model):
    nombre = models.CharField(max_length=8, blank=True, null=True)

    def __str__(self):
        return f'{self.nombre}'


class TipoSexo(models.Model):
    nombre = models.CharField(max_length=8, blank=True, null=True)

    def __str__(self):
        return f'{self.nombre}'


class Paciente(models.Model):
    tipo_usuario = models.ForeignKey(
        TipoUsuario, verbose_name='Tipo de usuario', on_delete=models.PROTECT)
    tipo_sangre = models.ForeignKey(
        TipoSangre, verbose_name='Tipo de sangre', on_delete=models.PROTECT)
    tipo_sexo = models.ForeignKey(
        TipoSexo, verbose_name='Tipo de sexo', on_delete=models.PROTECT)
    nombre = models.CharField(max_length=25)
    apellido = models.CharField(max_length=100)
    telefono = models.CharField(max_length=10, blank=True, null=True)
    foto = models.ImageField(
        upload_to='fotopaciente/%Y/%m/%d', null=True, blank=True)
    email = models.EmailField(
        verbose_name='correo electronico', blank=True, null=True)
    empresa = models.CharField(max_length=150, blank=True, null=True)

    def __str__(self):
        return f'id: {self.id} Usuario: {self.nombre} tipo usuario: {self.tipo_usuario}'


class DatosGeneral(models.Model):
    propietario = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    celular = models.CharField(max_length=10, blank=True, null=True)
    telefono = models.CharField(max_length=10, blank=True, null=True)
    domicilio = models.CharField(max_length=150, blank=True, null=True)
    ciudad = models.CharField(max_length=150, blank=True, null=True)
    estado = models.CharField(max_length=150, blank=True, null=True)
    cp = models.PositiveIntegerField(blank=True, null=True)
    lugar_nacimiento = models.CharField(max_length=150, blank=True, null=True)
    ocupacion = models.CharField(max_length=50, blank=True, null=True)
    region = models.CharField(max_length=50, blank=True, null=True)
    clave_app = models.CharField(max_length=10, blank=True, null=True)
    datofiscal = models.FileField(
        upload_to='datofiscal/%Y/%m/%d', null=True, blank=True, verbose_name='Curriculum vitae')

    def __str__(self):
        return f'Id: {self.id} {self.propietario}'


class Preferencia(models.Model):
    propietario = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    experiencia = models.TextField(
        max_length=200, null=True, blank=True, verbose_name='')
    nombre_pareja = models.CharField(
        max_length=25, blank=True, null=True, verbose_name="")
    fecha_aniversario = models.DateField(
        blank=True, null=True, verbose_name='')
    nombre_hijos = models.CharField(
        max_length=25, blank=True, null=True, verbose_name="")
    fecha_hijo = models.DateField(blank=True, null=True, verbose_name="")
    nombre_empresa = models.CharField(
        max_length=50, blank=True, null=True, verbose_name="")
    gustos = models.CharField(
        max_length=50, blank=True, null=True, verbose_name="")
    fecha_empresa = models.DateField(blank=True, null=True, verbose_name="")
    deportes = models.CharField(
        max_length=150, blank=True, null=True, verbose_name="")
    pelicula_serie = models.CharField(
        max_length=150, blank=True, null=True, verbose_name="")
    musica = models.CharField(
        max_length=150, blank=True, null=True, verbose_name="")
    vehiculo = models.CharField(
        max_length=150, blank=True, null=True, verbose_name="")
    comida = models.CharField(
        max_length=150, blank=True, null=True, verbose_name="")


class NotaPaciente(models.Model):
    propietario = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    alergias = models.CharField(max_length=250, blank=True, null=True)
    expectativas = models.CharField(max_length=250, blank=True, null=True)
    pade_actual = models.CharField(max_length=250, blank=True, null=True)
    observaciones = models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        return f'{self.propietario}'


class AntecedentePersonal(models.Model):
    propietario = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    casa = models.CharField(max_length=25, blank=True, null=True)
    lav_dientes = models.CharField(max_length=25, blank=True, null=True)
    tipo_pasta = models.CharField(max_length=25, blank=True, null=True)
    amalgama_puente = models.CharField(max_length=25, blank=True, null=True)
    brakets = models.CharField(max_length=25, blank=True, null=True)
    actividad_fisica = models.CharField(max_length=25, blank=True, null=True)
    ultima_desparacita = models.CharField(max_length=25, blank=True, null=True)
    inmunizaciones = models.CharField(max_length=25, blank=True, null=True)
    check_up = models.CharField(max_length=25, blank=True, null=True)

    def __str__(self):
        return f'{self.propietario}'


class AntecedenteFamiliar(models.Model):
    propietario = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    hermanos = models.PositiveIntegerField(default=0)
    diabetes = models.CharField(max_length=25, blank=True, null=True)
    hip_arterial = models.CharField(max_length=25, blank=True, null=True)
    cardiopatias = models.CharField(max_length=25, blank=True, null=True)
    hepatopatias = models.CharField(max_length=25, blank=True, null=True)
    urologicos = models.CharField(max_length=25, blank=True, null=True)
    neurologicos = models.CharField(max_length=25, blank=True, null=True)
    respiratorios = models.CharField(max_length=25, blank=True, null=True)
    cancer = models.CharField(max_length=25, blank=True, null=True)
    alergias = models.CharField(max_length=25, blank=True, null=True)
    metabolicas = models.CharField(max_length=25, blank=True, null=True)
    sanguineas = models.CharField(max_length=25, blank=True, null=True)
    articulares = models.CharField(max_length=25, blank=True, null=True)
    inmunologicas = models.CharField(max_length=25, blank=True, null=True)
    malformaciones = models.CharField(max_length=25, blank=True, null=True)
    dermatologicas = models.CharField(max_length=25, blank=True, null=True)
    otros = models.CharField(max_length=25, blank=True, null=True)

    def __str__(self):
        return f'{self.propietario}'


class AntecedentePatologico(models.Model):
    propietario = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    enf_infancia = models.CharField(max_length=25, blank=True, null=True)
    diabetes = models.CharField(max_length=25, blank=True, null=True)
    hip_arterial = models.CharField(max_length=25, blank=True, null=True)
    respiratorias = models.CharField(max_length=25, blank=True, null=True)
    oftalmico = models.CharField(max_length=25, blank=True, null=True)
    cardeovasculares = models.CharField(max_length=25, blank=True, null=True)
    neurologicos = models.CharField(max_length=25, blank=True, null=True)
    gastro_intestinal = models.CharField(max_length=25, blank=True, null=True)
    hepaticas = models.CharField(max_length=25, blank=True, null=True)
    metabolicas = models.CharField(max_length=25, blank=True, null=True)
    urologicos = models.CharField(max_length=25, blank=True, null=True)
    circulatorio = models.CharField(max_length=25, blank=True, null=True)
    traumaticas = models.CharField(max_length=25, blank=True, null=True)
    articulares = models.CharField(max_length=25, blank=True, null=True)
    dermatologicas = models.CharField(max_length=25, blank=True, null=True)
    quirurgicas = models.CharField(max_length=25, blank=True, null=True)
    transfusionales = models.CharField(max_length=25, blank=True, null=True)
    alergias = models.CharField(max_length=25, blank=True, null=True)
    vectores = models.CharField(max_length=25, blank=True, null=True)
    autoimunes = models.CharField(max_length=25, blank=True, null=True)
    emocionales = models.CharField(max_length=25, blank=True, null=True)
    adicciones = models.CharField(max_length=25, blank=True, null=True)
    hosp_previas = models.CharField(max_length=25, blank=True, null=True)
    pesticidas = models.CharField(max_length=25, blank=True, null=True)
    dx_ca = models.CharField(max_length=25, blank=True, null=True)
    otros = models.CharField(max_length=25, blank=True, null=True)

    def __str__(self):
        return f'{self.propietario}'


class AntecedenteAlimenticio(models.Model):
    propietario = models.OneToOneField(Paciente, on_delete=models.CASCADE)
    #  = models.CharField(max_length=50, blank=True, null=True)
    # comidaa = MultiSelectField(choices=COMIDAS)
    # my_field = MultiSelectField(choices=MY_CHOICES)
    # comidas = MultiSelectField(
    #     choices=MY_CHOICES2, max_choices=6, max_length=6, blank=True, null=True)
    desayuno = models.BooleanField(default=False)
    almuerzo = models.BooleanField(default=False)
    comida = models.BooleanField(default=False)
    cena = models.BooleanField(default=False)
    colaciones = models.BooleanField(default=False)
    tortillas = models.CharField(max_length=25, blank=True, null=True)
    pan = models.CharField(max_length=25, blank=True, null=True)
    cereales = models.CharField(max_length=25, blank=True, null=True)
    refrescos = models.CharField(max_length=25, blank=True, null=True)
    jugos = models.CharField(max_length=25, blank=True, null=True)
    aguas_frescas = models.CharField(max_length=25, blank=True, null=True)

templates/paciente/recursos/cardcumple.html
{% load static %}
{% now "Y-m-d" as current_datetime %}
<div class="card-header" role="tab" id="tabCumpleanios">
    <a class="collapsed" data-toggle="collapse" data-parent="#tablerosPacientes" href="#tableroCumpleanios"
        aria-expanded="false" aria-controls="tableroCumpleanios">
        <h5 class="mb-0 h6 text-muted text-left">
            <i class="fas fa-birthday-cake"></i> Cumpleaños
        </h5>
    </a>
</div>

<div id="tableroCumpleanios" class="collapse" role="tabpanel" aria-labelledby="tabCumpleanios"
    data-parent="#tablerosPacientes">
    <div class="card-body">
        <div id="divCumpleanios">
            {% for paciente in pacientes %}
                {% if paciente.datosgeneral.fecha_nacimiento != None and paciente.datosgeneral.fecha_nacimiento|date:"Y-m-d" == current_datetime %}
                    <div class="row mt-2" style="border-bottom-style: solid; border-width: thin; border-color: #ccc;">
                        <div class="col-4 col-md-4">
                            <a href="{% url 'editarpaciente' paciente.id %}" target="_self">
                                {% if paciente.foto == "" %}
                                <!-- <img src="../../img/sinfoto.png" class="img-fluid z-depth-1 rounded"> -->
                                <img src="{% static 'img/' %}sinfoto.png" class="img-fluid z-depth-1 rounded">
                                {% else %}
                                <img src="{{paciente.foto.url}}" class="img-fluid z-depth-1 rounded">
                                {% endif %}
                                <div class="spinner-grow text-secondary" role="status">
                                    <span class="sr-only">Loading...</span>
                                </div>
                            </a>
                        </div>

                        <div class="col-8 col-md-8 ">
                            <a href="{% url 'editarpaciente' paciente.id %}" target="_self" class="text-dark">

                                <b>
                                    {{paciente.nombre}} {{paciente.apellido}}
                                </b>

                            </a>
                            <br>

                            <a href="https://api.whatsapp.com/send?phone=+52{{paciente.telefono }}&amp;text=Felíz cumpleaños, Obed, hoy es tu gran día y solo quiero desearte felicidad y alegría"
                                target="_blank" class="text-dark">
                                <small>
                                    <i class="fas fa-birthday-cake text-secondary"></i>
                                    {{paciente.datosgeneral.fecha_nacimiento }}<span class="ml-3">0 años</span> <br>
                                    {% if paciente.datosgeneral.domicilio != None %}
                                    <i class="fas fa-home text-danger mr-2"></i> {{paciente.datosgeneral.domicilio}}
                                    <br>
                                    {% endif %}
                                </small>
                            </a>


                            <small>
                                {% if paciente.telefono != none %}
                                <a href="tel:+52{{paciente.telefono}}" class="text-dark mr-3">
                                    <i class="fas fa-phone-volume text-info mr-2"></i>
                                    {{paciente.telefono}} </a>
                                {% endif %}

                                {% if paciente.telefono != none %}
                                <a href="https://api.whatsapp.com/send?phone=+52{{paciente.telefono}}&amp;text=Felíz cumpleaños, Obed, hoy es tu gran día y solo quiero desearte felicidad y alegría"
                                    target="_blank" class="text-dark mr-3">
                                    <i class="fab fa-whatsapp text-success mr-2"></i>
                                    {{paciente.telefono}} </a>
                                {% endif %}
                                <br>
                                {% if paciente.email != none %}
                                <a href="mailto:{{paciente.email}}" class="text-dark">
                                    <i class="far fa-envelope text-info mr-2"></i>
                                    {{paciente.email}} </a>
                                {% endif %}

                            </small>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}

        </div>
    </div>
</div>

templates/paciente/recursos/cardproximaconsulta.html
<div class="card-header" role="tab" id="tabProximaConsulta">
    <a class="collapsed" data-toggle="collapse" data-parent="#tablerosPacientes" href="#tableroProximaConsulta"
        aria-expanded="false" aria-controls="tableroProximaConsulta">
        <h5 class="mb-0 h6 text-muted text-left">
            <i class="far fa-calendar-check"></i> Próximas Consultas
        </h5>
    </a>
</div>
<div id="tableroProximaConsulta" class="collapse" role="tabpanel" aria-labelledby="tabProximaConsulta"
    data-parent="#tablerosPacientes">
    <div class="card-body">
        <div id="divProximaConsulta">
            <table class="table table-hover table-responsive-sm table-fixed">
                <tbody>
                    {% for paciente in pacientes %}
                    <tr>
                        <td style="padding-left: 0; padding-right: 0;padding-top: 4px; padding-bottom: 1px;">
                            <a href="{% url 'editarpaciente' paciente.id %}" target=" _self">
                                {% if paciente.foto == "" %}
                                <i class="fas fa-image text-muted fa-4x"></i>
                                {% else %}
                                <img src="{{paciente.foto.url}}" class="img-fluid z-depth-1 rounded">
                                {% endif %}
                            </a>
                        </td>
                        <td style="font-size: 13px;">
                            <div class="row">
                                <div class="col-12">
                                    <a href="{% url 'editarpaciente' paciente.id %}" target="_self">
                                        {{paciente.nombre}} {{paciente.apellido}} </a>
                                </div>
                                <div class="col-12 text-danger ">
                                    <strong>
                                        Última Consulta 24/02/2023 </strong>
                                </div>
                                <div class="col-12">
                                    {% if paciente.email != none %}
                                    <a href="mailto:{{paciente.email}}">
                                        <i class="far fa-envelope"></i>
                                        {{paciente.email}} </a>
                                    {% endif %}
                                </div>
                                <div class="col-12">
                                    {% if paciente.telefono != none %}
                                    <a href="https://api.whatsapp.com/send?phone=+52{{paciente.telefono}}&amp;text=Hola, Abigail, queremos recordarte que tienes un saldo pendiente de $0.00"
                                        target="_blank">
                                        <i class="fab fa-whatsapp"></i>
                                        {{paciente.telefono}} </a>
                                    {% endif %}

                                </div>
                            </div>

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>

                <thead class="lighten-3">
                    <tr>
                        <th width="62px;"></th>
                        <th style="font-size: 13px;">Paciente</th>
                    </tr>
                </thead>
            </table>
        </div>

    </div>
</div>

templates/paciente/recursos/formhabitosalim.html
<div class="col-12 col-md-12 mt-2">
    <div class="card">
        <div class="card-body">
            <div class="row">
                {% load crispy_forms_tags %}
                <div class="col-12">
                    <h6 class="h6 text-muted text-center">Hábitos
                        Alimenticios</h6>
                </div>
                <div class="col-12">
                    <form id="formhalimenticio" action="{% url 'editaralimenticio' paciente.id %}" method="POST">
                        {% csrf_token %}
                        <div id="habitosAlimenticios">

                            <div class="row" style="justify-content: center;">
                                <div class="form-check form-check-inline ms-3">
                                    {{formalimenticio.desayuno}}
                                     <label class="form-check-label" for="id_desayuno"> Desayuno</label>
                                </div>
                                <div class="form-check form-check-inline ms-3 ">
                                    {{formalimenticio.almuerzo}}
                                     <label class="form-check-label" for="id_almuerzo"> Almuerzo</label>
                                </div>
                       
                                <div class="form-check form-check-inline ms-3">
                                    {{formalimenticio.comida}}
                                     <label class="form-check-label" for="id_comida"> Comida</label>
                                </div>
                                <div class="form-check form-check-inline ms-3 ">
                                    {{formalimenticio.cena}}
                                     <label class="form-check-label" for="id_cena"> Cena</label>
                                </div>
                                <div class="form-check form-check-inline ms-3 ">
                                    {{formalimenticio.colaciones}}
                                     <label class="form-check-label" for="id_colaciones"> Colaciones</label>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Tortillas</small>
                                    {{formalimenticio.tortillas}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Pan</small>
                                    {{formalimenticio.pan}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Cereales</small>
                                    {{formalimenticio.cereales}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Refrescos</small>
                                    {{formalimenticio.refrescos}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Jugos</small>
                                    {{formalimenticio.jugos}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Aguas Frescas</small>
                                    {{formalimenticio.aguas_frescas}}

                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Frutas</small>
                                    {{formalimenticio.frutas}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Frutos Secos</small>
                                    {{formalimenticio.frutos_secos}}
                                </div>
                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Verduras</small>
                                    {{formalimenticio.verduras}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Agua Natural</small>
                                    {{formalimenticio.agua_natural}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Golosinas</small>
                                    {{formalimenticio.golosinas}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Carnes Rojas</small>
                                    {{formalimenticio.carnes_rojas}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Pollo</small>
                                    {{formalimenticio.pollo}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Pescado</small>
                                    {{formalimenticio.pescado}}

                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Mariscos</small>
                                    {{formalimenticio.mariscos}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Leche</small>
                                    {{formalimenticio.leche}}

                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Derivados</small>
                                    {{formalimenticio.derivados}}

                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Huevo</small>
                                    {{formalimenticio.huevos}}

                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Arroz</small>
                                    {{formalimenticio.arroz}}

                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Legumbres</small>
                                    {{formalimenticio.legumbres}}

                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Miel</small>
                                    {{formalimenticio.miel}}

                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Aceite</small>
                                    {{formalimenticio.aceite}}

                                </div>


                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Sal</small>
                                    {{formalimenticio.sal}}

                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Azucar</small>
                                    {{formalimenticio.azucar}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Café</small>
                                    {{formalimenticio.cafe}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Té</small>
                                    {{formalimenticio.te}}

                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">

                                    <small>Sazonadores</small>
                                    {{formalimenticio.sazonadores}}

                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Embutidos</small>
                                    {{formalimenticio.embutidos}}

                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Enlatados</small>
                                    {{formalimenticio.enlatados}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Pastas</small>
                                    {{formalimenticio.pastas}}

                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Suplementos y Energéticos</small>
                                    {{formalimenticio.sumplementos_energe}}
                                </div>

                                <div class="col-6 col-lg-2 col-md-3 mt-1 text-center">
                                    <small>Otros</small>
                                    {{formalimenticio.otros}}

                                </div>



                            </div>

                            <div id="resHabitos"></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>